{% set name = "aloe" %}
{% set version = "0.1.15" %}
{% set sha256sum = '1ce12bbbef69063c6222042b42a3cd2ce7b9fbe817b2330609678a98b58c2a38' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm

  run:
    - python
    - nose
    - future
    - gherkin-official >=4,<5
    - nose
    - repoze.lru

test:
  imports:
    - aloe

about:
  home: https://github.com/aloetesting/aloe
  license: GPL-3.0
  # xref: https://github.com/aloetesting/aloe/pull/129
  # license_file: '{{ environ["RECIPE_DIR"] }}/COPYING'
  license_file: COPYING
  summary: Behavior Driven Development using Cucumber for Python

extra:
  recipe-maintainers:
    - mariusvniekerk
