# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "LLhdPXdPNhypuXW+zQvALZhkMB7nthn+2jY0hpoXqOj7FyS62BiFMd2+Tkdbp754IpOoDhIKH4KGzUci4MqCIIGHWOvkRIffE9eHJlA9e0+60K+sMCUNLuc1dORulsDr2vDYDWnMPktaSzRP3pbquc/1umT7uYWJr7DfVARZemsz267rbQGARypek57nBuJiCd5JiE9NizdL/ZTSV5U/GP2Dn+46GAAhaTJ/AiBsQrvFvbqiWBWrvM6GnS3dnQhQm8hXPj6Vzb8w1fR4T+ApyVSHcGvU/BTtAi/zhCw1T9s/S39h+97gvnZSRn61wGvwOdKGAQWK0/ZB3hld5hfQ1j2kXvq8E888aDv5HCnRCfQR9X2ytImMmY7dIks6u44cSmdWjp50xr5gc5597C2Kd2m9gQVpNtKEKpp0egPbumDsKF4+SVK/WFG27ic6KGCsxJCdQo3HL3zLOC713GtNi7TGPRI5xB2de23eL0MaVpUSDetZt7fWHapG4UV4tAAhG1KI1bumGE4kP5Xvwp4FUUlrwsOmbEWYMmbrMq16dEYESgXo6PK+AM6NlM7VsILIegNOjbruxmqNjrZgCaqFi2NNPSyYwKBneg/oabh759aarCNYstn0NBA6oeXjg29NfIswG4fwZ13EYPXeyIljtBYko0WG9bTuGjmePZLiUC0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
