travis:
  secure:
    BINSTAR_TOKEN: LLhdPXdPNhypuXW+zQvALZhkMB7nthn+2jY0hpoXqOj7FyS62BiFMd2+Tkdbp754IpOoDhIKH4KGzUci4MqCIIGHWOvkRIffE9eHJlA9e0+60K+sMCUNLuc1dORulsDr2vDYDWnMPktaSzRP3pbquc/1umT7uYWJr7DfVARZemsz267rbQGARypek57nBuJiCd5JiE9NizdL/ZTSV5U/GP2Dn+46GAAhaTJ/AiBsQrvFvbqiWBWrvM6GnS3dnQhQm8hXPj6Vzb8w1fR4T+ApyVSHcGvU/BTtAi/zhCw1T9s/S39h+97gvnZSRn61wGvwOdKGAQWK0/ZB3hld5hfQ1j2kXvq8E888aDv5HCnRCfQR9X2ytImMmY7dIks6u44cSmdWjp50xr5gc5597C2Kd2m9gQVpNtKEKpp0egPbumDsKF4+SVK/WFG27ic6KGCsxJCdQo3HL3zLOC713GtNi7TGPRI5xB2de23eL0MaVpUSDetZt7fWHapG4UV4tAAhG1KI1bumGE4kP5Xvwp4FUUlrwsOmbEWYMmbrMq16dEYESgXo6PK+AM6NlM7VsILIegNOjbruxmqNjrZgCaqFi2NNPSyYwKBneg/oabh759aarCNYstn0NBA6oeXjg29NfIswG4fwZ13EYPXeyIljtBYko0WG9bTuGjmePZLiUC0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
