travis:
  secure:
    BINSTAR_TOKEN: XA17m9mYO+MFQV86Ooj3yXJLjO/UwWAY8lizfXucjo9mSlD+LLqulAhC2gSMMXUA1zSfs8U7ZZNMYxukY4SeXE2eW+kJ/jWsMUbDREOhGpImmJW1dWL/XycEsDeQWJPLcjni5FxnuKIOjBELXd2QRAFsM7EFPFpqLdezzDVE8PYB6YfymqWId64tB4VA7IOEci5ZqbX6VSkKrOnei0cfnWDIMbXKPcHCbBXBk5jxVkIRFdGZioNsS+92hu4XdLWYfTqkuXwZBewy8tj8wHVlaW1yXaf+gyd6R0gaUy7vEm7BppuEnHxdrrD0KXVl0NqCVOdT2LFA3c0gF0fQtMXnvc/U/zf38RA8pl70EAQY17T/53/zT/kTrHKKVJqHVAvEUx9nBzOc2/RE3UXUuc7L8l5gtaDdh88TEdJ+Tk/l/ppLNPesRsJLEhvLhDBjM3VChUYJZ7LRvbuNG3AzmQDd5VfoEZGrCzpcK9VZix6s6sMmgFYpwk8XMSZPyXVRM8I6nyfqG8Ky0UFcWj56riOGZlN8EnF5spCxY6lj0lZhP5kwYH9FgE0GJZFSS2Qyxsrz82U+pWfIE/Xw1385BIMAuPA8Yoqmu2y5pyCLiPmsQ8bjnWDeinkOLTxAc/e9J23i5ww7igGglKwDSJaUTOIsXNCYWi7I2SEf5dQ6GDvp1hI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
